import { StockDataPoint, StockItem } from "../../types/types";

interface StockData extends StockItem {
    data: StockDataPoint[];
  }

export let mockData: StockData[][] = [
    [
      {
        id: 1,
        symbol: "SPXUSD",
        name: "S&P 500",
        price: 4290.6,
        change: 12.3,
        changePercentage: "+0.29%",
        color: "#009376",
        data: [],
      },
      {
        id: 2,
        symbol: "NSXUSD",
        name: "US 100",
        price: 14607.5,
        change: 44.1,
        changePercentage: "+0.30%",
        color: "#FF018C",
        data: [],
      },
      {
        id: 3,
        symbol: "DJI",
        name: "Dow 30",
        price: 33733.5,
        change: 73.5,
        changePercentage: "+0.22%",
        color: "#002E3C",
        data: [],
      },
      {
        id: 4,
        symbol: "NKY",
        name: "Nikkei 225",
        price: 32371.9,
        change: -56.85,
        changePercentage: "-0.18%",
        color: "#0299eb",
        data: [],
      },
      {
        id: 4,
        symbol: "NKY",
        name: "Nikkei 225",
        price: 32371.9,
        change: -56.85,
        changePercentage: "-0.18%",
        color: "#0299eb",
        data: [],
      },
      {
        id: 5,
        symbol: "FTSE",
        name: "FTSE 100",
        price: 7050.5,
        change: -12.5,
        changePercentage: "-0.18%",
        color: "#2C3E50",
        data: [],
      },
      {
        id: 6,
        symbol: "DAX",
        name: "DAX 30",
        price: 15300.2,
        change: 23.9,
        changePercentage: "+0.16%",
        color: "#3498DB",
        data: [],
      },
      {
        id: 7,
        symbol: "CAC",
        name: "CAC 40",
        price: 6820.1,
        change: 15.1,
        changePercentage: "+0.22%",
        color: "#E67E22",
        data: [],
      },
      {
        id: 8,
        symbol: "ASX",
        name: "ASX 200",
        price: 7400.9,
        change: -7.6,
        changePercentage: "-0.10%",
        color: "#16A085",
        data: [],
      },
    ],
    [
      {
        id: 9,
        symbol: "HSI",
        name: "Hang Seng",
        price: 24300.3,
        change: 55.2,
        changePercentage: "+0.23%",
        color: "#C0392B",
        data: [],
      },
      {
        id: 10,
        symbol: "SSE",
        name: "Shanghai Composite",
        price: 3500.5,
        change: 4.3,
        changePercentage: "+0.12%",
        color: "#8E44AD",
        data: [],
      },
      {
        id: 11,
        symbol: "TSX",
        name: "TSX",
        price: 20430.1,
        change: -35.1,
        changePercentage: "-0.17%",
        color: "#2980B9",
        data: [],
      },
      {
        id: 12,
        symbol: "AEX",
        name: "AEX",
        price: 725.3,
        change: 8.5,
        changePercentage: "+1.18%",
        color: "#27AE60",
        data: [],
      },
      {
        id: 13,
        symbol: "BSE",
        name: "BSE SENSEX",
        price: 59000.8,
        change: 140.7,
        changePercentage: "+0.24%",
        color: "#E74C3C",
        data: [],
      },
      {
        id: 14,
        symbol: "KOSPI",
        name: "KOSPI",
        price: 3000.2,
        change: -21.2,
        changePercentage: "-0.70%",
        color: "#9B59B6",
        data: [],
      },
    ],
    [
      {
        id: 15,
        symbol: "RTSI",
        name: "RTS Index",
        price: 1450.7,
        change: -10.5,
        changePercentage: "-0.72%",
        color: "#34495E",
        data: [],
      },
      {
        id: 16,
        symbol: "IBEX",
        name: "IBEX 35",
        price: 8900.9,
        change: 23.1,
        changePercentage: "+0.26%",
        color: "#F39C12",
        data: [],
      },
      {
        id: 17,
        symbol: "OMX",
        name: "OMX Stockholm 30",
        price: 2500.4,
        change: -8.1,
        changePercentage: "-0.32%",
        color: "#D35400",
        data: [],
      },
      {
        id: 18,
        symbol: "MIB",
        name: "FTSE MIB",
        price: 27000.3,
        change: 35.6,
        changePercentage: "+0.13%",
        color: "#1ABC9C",
        data: [],
      },
      {
        id: 19,
        symbol: "SMI",
        name: "Swiss Market Index",
        price: 12250.1,
        change: -5.2,
        changePercentage: "-0.04%",
        color: "#BDC3C7",
        data: [],
      },
      {
        id: 20,
        symbol: "TA35",
        name: "TA-35",
        price: 1800.9,
        change: 9.7,
        changePercentage: "+0.54%",
        color: "#7F8C8D",
        data: [],
      },
    ],
  ];